common/moss.py
web/views/teacher.py

Pokud MOSS vrátil `matches = []`, tak `if ... or cache.get(key)` vrátí False, takže se bude ten job resubmittovat pořád dokola. Zároveň jsem radši přidal timeout a vyčistil job z cache, aby tam nevyhníval (např. kdyby MOSS job failnul uprostřed, tak by se ta job cache nikdy nevyčistila a nešlo by MOSS znovu spustit).
Bylo by asi taky fajn to spouštění toho jobu dělat jenom při POST a nastavit POST na `MOSS check` tlačítko.

Fix MOSS job timeout and result check

---

web/static/style.css

`break-all` nebyl dobrý nápad :D Lomí to někdy fakt hnusně.

Use break-word instead of break-all in comments

---

frontend/src/ClassDetail.svelte

I have too many tasks :D I want to see all of the assignments and points right away.

Hide task names in class detail by default

---

templates/web/task_detail.html
web/views/student.py

When new submits arrive, it's useful to see which ones were already commented.

Show commment count on Source code tab

---

common/moss.py
templates/web/moss.html
web/views/teacher.py

This PR reworks how MOSS jobs are handled. What is changed:
1) MOSS jobs are no longer auto-started automatically when you visit the MOSS page to avoid fail-retry chains resulting in many requests to the MOSS server. There is now an explicit button.
2) If a MOSS job fails (either an exception is raised inside the job or the queue somehow misplaces the job), the corresponding job cache key will be kept until you view the page again. When you open the page, the corresponding error (with an exception chain) will be printed and the job (its cache entry) will be removed, so that you can re-submit the job again after reload of the page. In this situation the automatic refresh will be disabled, so that you can read the error.
3) When a new job is submitted, the previous result is deleted. This …

Improve handling of failed MOSS jobs and add timestamp to job result

---

evaluator/images/gcc/entry.py

Use case:
- parallel build (`-j 2`)
- build only selected target to speed up evaluation (`make <target>`)

Add the possibility to specify make flags in the `gcc` image

---

README.md
README.pipeline.md
evaluator/images/base/Dockerfile
evaluator/images/dotnet/Dockerfile
evaluator/images/dotnet/entry.py
evaluator/images/pythonrun/Dockerfile
evaluator/images/run/Dockerfile
evaluator/pipelines.py
frontend/src/PipelineValidation.js

It wasn't straightforward to get it working, but hopefully something like this should work for simple projects. Network access has to be enabled in order to build a standalone binary, sadly. We could get around it by building a .NET framework dependent binary, but then all additional steps (like `run`, `tests` etc.) would need to be executed inside Docker, which is annoying.

Add support for compiling `.NET` projects

---

evaluator/images/dotnet/entry.py

Before it was crashing because `output` was `None`.

Properly print error in dotnet builds

---

evaluator/images/dotnet/Dockerfile
evaluator/images/dotnet/entry.py

Since the upgrade to Dotnet 6.0.10, there was a permission denied error (https://github.com/dotnet/core/issues/7868). The version of dotnet is now also pinned in the Dockerfile.

Set XDG_DATA_HOME when executing dotnet command

---

evaluator/images/dotnet/entry.py

Now we try to find a `.csproj` file with `OutputType` set to `Exe`, and use its name for searching for the binary.

Improve support for multiple projects in dotnet pipeline

---

frontend/src/Comment.svelte
frontend/src/TaskDetail.svelte

On the teacher's page, where user submissions are displayed, comments can overlap with the quick buttons on the right.
What it looked like before: https://ctrlv.link/cLNp
What does it look like now after the fix: https://ctrlv.link/WRcl
If new icons were added in the future, it would look like this: https://ctrlv.link/LXYL

Fix - Overlapping icons #175

---

frontend/src/Notifications.svelte

Disabling `draggable` attribute on notification icon so that the icon can't be dragged and submitted when released, like happened to me. The submitted work looks like this:

Disabling `draggable` attribute

---

templates/web/moss.html

I misunderstood how it worked, it should be enabled, because it only shows entries where at least one of the students is from the current semester, which is what we want.

Set "Show this semester only" to be checked by default again

---

common/moss/__init__.py
web/views/moss.py

Before, MOSS result matches were automatically filtered and the match list was indexed by match ID. However, if some entries were filtered (which happened almost all the time), indexing by ID would yield incorrect results. Now matches are looked-up using their ID instead of using it directly as a list index.
Additionally, MOSS results can now be displayed for results that do not pass through the currently active filter. Adding the flag is dirty, but the `MossResult` API would need to be refactored completely to solve this easily in a different way.

Fix displaying of MOSS sources

---

frontend/src/SubmitsDiff.svelte
web/views/student.py

Svelte sadly doesn't support whitespace trimming between tags, so I implemented the formatting of the info row in JavaScript.
Fixes: https://github.com/mrlvsb/kelvin/issues/177

Add comment count to submit diff

---

frontend/src/TaskDetail.svelte
web/views/student.py

It is nice to know quickly whether some file has user comments. But at the same time, for students it's useful to see automated comments too. So I split the comment counter into two.
Fixes: https://github.com/mrlvsb/kelvin/issues/176

Separate comment count badges for user and bot comments

---

evaluator/images/cargo/Dockerfile
evaluator/images/cargo/entry.py
frontend/src/PipelineValidation.js

Can be used with `cargo build`, `cargo test`, `cargo run`, `cargo clippy` etc. It also prepares an executable (if available) under the filepath `main`, to be used with follow-up `run` pipelines.

Add `cargo` pipeline

---

templates/web/index.html

The task table currently doesn't look really well on mobile with unbreakable task names. Added a `div` with `table-responsive` class to make it scroll-able if needed. The rest of the diff is just indentation.
https://github.com/mrlvsb/kelvin/assets/18398260/0303bfc7-256c-47b2-857a-285ba9a9c866

Making the task table responsive

---

evaluator/pipelines.py

The default limits didn't allow downloading crates from crates.io, and also caused OOM/disk errors even for simple code.

Increase default pipeline limits for Cargo

---

evaluator/results.py
templates/web/report.html

To keep `stdin` before `stdout` in a deterministic way. This code should live in the view/presenter, but Django doesn't really make that easy…

Sort files in test results

---

evaluator/images/java/Dockerfile
evaluator/images/java/entry.py
evaluator/pipelines.py
frontend/src/PipelineValidation.js

Docker image for Java evaluator.

Support for Java language 

---

web/views/assets/run-tests.sh
web/views/student.py

To simplify local testing, a bash script was created. It compares the executable's standard output with `stdout` file (and similarly for `stderr`). On differences a `git diff` output is saved. It is now included with every downloaded archive of all tests. Due to many different types of tasks `args` are bundled as a separate file and if it is present, then it is passed to executable.

Include runner script in tests archive

---

frontend/src/Modal.svelte
frontend/src/UploadSolution.svelte

When dropping files to browser, a question modal is shown to make sure user really wants to submit these files. Modal also contains list of dropped files.
Example:
However, in some cases, I received this file list and I think I can't impact that behavior since these uploads will fail.
The modal component was retrieved and modified from https://eternaldev.com/blog/using-bootstrap-modal-in-svelte.

Ask before uploading dropped solution

---

frontend/src/UploadSolution.svelte

Show confirmation toast after successful submit

---

web/views/assets/run-tests.sh

The file existence condition was useless because of running `realpath` before checking path existence.
Script paths were improved to allow running outside of a current directory.
A check for git existence was added. (Why don't just everyone use git though?)
Since we have some macOS users with really weird default terminal, the ANSI escape sequences were replaced with `tput` command.

Improve path handling in `run-tests.sh` script

---

frontend/src/ClassDetail.svelte
frontend/src/ClassFilter.svelte
templates/web/index.html

In my opinion, options like `Semester` etc. should not be selected since they are representing some kind of heading. I have set them to `disabled`. We could alternatively use `optgroup` for that, but that's a small detail.
I also found some Czech word in student index template. I have replaced that with this commit because it was just minimal change for a separate commit :)

Disable default select options

---

evaluator/images/dotnet/entry.py

In new versions of .NET, it is unfortunately possible for the *.sln file to be in the directory of one of the projects (and still references another project).
So for example:
- project1
- project1.csproj
- project.sln
- project2
- project2.csproj
This change is supposed to be a fallback that addresses one special case. It also addresses the inability of students to upload the correct directory structure.

Fix for nested *.sln files

---

frontend/src/EditTask.svelte
frontend/src/TimeRange.svelte

Closes #386.
When a callback is set for duplicate buttons (`onFromDuplicateClick`, `onToDuplicateClick`), these buttons are displayed. The callbacks should accept one argument: the date to be assigned. The buttons can also be disabled using props `fromDuplicateDisabled` and `toDuplicateDisabled`.
The extra props in `TimeRange` are optional and thus they need a default value.

Add duplicate buttons to TimeRange

---

frontend/src/PipelineStatus.svelte

Let students know thay can safely close the browser window and don't lose any data (submit).

Message after submit modified (#412)

---

templates/web/layout.html
web/urls.py

I propose few changes that aim to make the following possible:
- Teachers, who are also assigned as students in other classes, can now navigate to their _student view_ and therefore access such classes
- When making requests to class related API urls, the server will now return classes where the current user is teacher **or student** (while keeping this endpoint restricted to teachers only)
Let me know whether there are any further changes necessary. Thanks :)

Make student view available for teachers

---

requirements.txt

Sync of Python packages that are currently installed on production site that runs Python 3.12.
And yes, I know we need to use `pip-tools` or something similar (#405).

[Bump] Sync Python packages with ones on production

---

frontend/src/AssignmentPoints.svelte

I discovered this hard coded color code for quick point assignment overlay background (mobile feature). With this change it should always pull the correct color for light/dark mode right from Bootstrap, guaranteeing legibility.
Before (dark mode) |  After (dark mode)
:---------------------------:|:---------------------------:

Fix dark bg color of quick point assignment overlay

---

web/views/assets/run-tests.py

A few students reported that there's an error in `run-tests.py` script. I've added missing import of `Optional` to make it working. Tested on Python 3.12.1.

Add missing import in tests script

---

requirements.txt

Also changes name to use underscore to make PyCharm happy.

[Bump] typing_extensions

---

requirements.txt

Upgrading Pandas greatly reduces build time in Python 3.12. It also affects build time for Pyright workflow on GitHub. I tested functionality of statistics in Kelvin and there's no regression.

[Bump] Pandas

---

.github/workflows/pyright-venv.yml

At this pyright check fails on building dependencies. Also, building pandas `1.5.3` in the workflow takes a long time. We can upgrade it to `2.x` and speedup the process. I'll take a look at it.

Pyright virtual environment config

---

templates/web/layout.html

I am frustrated by prompts of my web browser thinking that Kelvin is in Danish language, that's why I added a `lang` attribute to `html` tag so it is clear for browsers.

Set site language

---

api/views.py
common/inbus/inbus.py
common/inbus/utils.py

Various typing enhancements in INBUS integration, code reformat, and import change.

Removed possible infinite loop in INBUS integration

---

common/inbus/inbus.py

This has to be elaborated on more thoughly in future. Prefarably syncing Kelvin semester with INBUS's ones in frontend selection. But it also waits for the new frondend implementation.

[Fix] SemesterId in INBUs API

---

pyproject.toml
requirements.txt
uv.lock
web/task_utils.py

Restores original `pandoc` behavior that allowed sublists to be indented with just 2 (and not 4) spaces.

Improve parsing of Markdown lists

---

evaluator/images/java/Dockerfile

Fixes: https://github.com/mrlvsb/kelvin/issues/527

Add support for Java 21 (#527)

---

api/views.py
frontend/src/Teacher/AllTasks.vue

- Added link task to title of task
- Increased default number of tasks per page to 25
- Pregenerate path to task

Small adjustements to Task Datatable

---

.github/workflows/ci.yml

PRs from forks don't have the necessary permissions to write to the build cache.
Fixes: https://github.com/mrlvsb/kelvin/issues/584

Disable Docker cache writes for pull requests

---

.env.example
kelvin/settings.py

Before, we were using a weird combination of the default Django settings and some overridden values.
Now, all logs are written to the console by default, and the format of Django and app logs is unified.

Make logging configuration consistent and remove file logging

---

evaluator/images/base/Dockerfile

When building the `base` image, docker build warns about depricated use of setting environment variable. This removes such warning.

Remove deprication warning in `base` image

---

evaluator/images/clang-tidy/build_urls.py

This is a hotfix to have correct Clang-Tidy checks identifiers in the JSON of URLs. Image rebuild required.
CC @Kobzol

Fix invalid keys of Clang-Tidy checks

---

api/views.py
frontend/src/Autocomplete.svelte

So, the good news is that this was easy to fix. The bad news is that it was broken even before we broke it recently =D The autocomplete tries to download all tasks from Kelvin (there are more than 3 thousand tasks at the moment), which is really not a good idea, and will not work.. It either needs to be reimplemented or we should remove it completely.
At the very least, it should only download tasks from the given subject. I will do that in a follow-up PR.
Related issue: https://github.com/mrlvsb/kelvin/issues/637

Fix missing `order_by` in task and student list

---

api/dto.py
api/urls.py
api/views/default.py
api/views/quiz.py
api/views/utils.py
quiz/models.py
quiz/quiz_utils.py

Added base components and business logic for quizzes. With this, it's possible to:
From teacher pov:
- CRUD operations on quiz model
- Edit content of quiz
- View quiz
- Assign quiz
- Score quiz
From student pov:
- Enroll quiz
- View quiz results
It's still not "integrated" into Kelvin UI, it's required to call endpoints directly. 
I apologize that this one is quite large, probably largest, but I believe it will not be problematic to read. The next ones will be divisible better.

Base components and business logic for quizzes

---

common/models.py

This allows us to modify task in the admin page without actually filling in plagiarism key.

Allow blank plagiarism key

---

web/views/student.py

Should be seen in tar archive when downloading archive of submit files.

Fix missing modify attribute for files in tar archive

---

deploy/nginx.conf
kelvin/settings.py
kelvin/storage.py

There is really no reason why we should be using uncompressed assets. We could also use Brotli/ZSTD, but Gzip should be enough as a start.
I already modified the nginx config in production.

Generate compressed static assets and dynamically compress HTML pages

---

web/views/student.py

In logs I can see that sometimes there is a user generated comment for a file that is not found. I'm not exactly sure how it can happen (maybe the file disappeared from disk or cannot be loaded?), but in any case we should not error out in that case. This hack moves the comment to the summary in that case.

Move comments for non-existent files to summary

---

deploy/nginx.conf

The invalid host exception was super spammy. I wanted to ignore it first, but I realized that denying these requests is a much better solution than them resulting in a 500 server error (this is kinda stupid behavior btw, Django should really return 400 errors for these...).

Do not allow connections through non-canonical hosts in nginx

---

deploy/nginx.conf

Exposed server information can lead attackers to find version-specific server vulnerabilities that can be used to exploit unpatched servers.

Hide nginx version

---

web/views/student.py

This has been appearing in the logs for a few years, I finally got annoyed enough to fix it.

Account for `None` returned from `job.get_position()`

---

api/views/default.py
frontend/src/ClassDetail.svelte
frontend/src/EditTask.svelte
frontend/src/TaskFilter.svelte
frontend/src/taskTypes.js

Fixes #600
Filters tasks by one task type in the main view, it also calculates the points for the type. 
Right now it looks like this

Added filtering of tasks based on a task types

---

frontend/src/ClassDetail.svelte

Fixes new bug found in my recenlty added feature.
Before
After

Fixed more content hover in Class Detail

---

frontend/src/EditTask.svelte
frontend/src/TimeRange.svelte

Fixes #551
This is the way that I understood relative deadline. You specify start and end in the first class, and the just specify the start of each of the other classes and then just copies the relative deadline. So the deadline would be Assigned + (diff from the one that it was clicked from).

Add relative deadline button

---

frontend/src/global.scss

Fixes #573
Updated 2 elements, 1 class with the greyish color. The td, th tags i think caused the main problem. The global color change wouldn't change the color of these elements, or atleast with my experiments it didn't.
Current state:

Changed white font color to grayish in dark mode

---

frontend/src/global.scss

Reverts mrlvsb/kelvin#673 because of bad readability in task detail in dark mode.

Revert "Changed white font color to grayish in dark mode"

---

api/views/default.py

This logic is brutal.. When a new task is being created, the `EditTask` components loads classes from `/api/subject`, and then monkey patches additional attributes to these classes, and then it resends the classes (which then actually represent assigned tasks) to `task_detail`. This should be rewritten from scratch =D
This PR is mostly a hotfix.
Fixes: https://github.com/mrlvsb/kelvin/issues/677

Handle missing `hard_deadline` in `task_detail`

---

evaluator/images/cargo/Dockerfile
evaluator/images/cargo/entry.py

Shouldn't be merged until the 1.90.0 Docker image is actually released (should be Thursday/Friday this week).

Update Cargo Docker image to 1.90.0

---

frontend/src/ClassDetail.svelte

I wasn't able to recreate the problem on the local, for me it worked without the hash, but this should fix the problem.
Seems like the use:link have problem with rerendering in use with the spa-router, please correct me if I am wrong :). 
Fixes #706

Fix of edit link in Class Detail

---

common/models.py
templates/web/task_detail.html
templates/web/teacher/form_assign_points.html
uv.lock
web/views/student.py

Suggested by @kozusznik.
The fetch of the submits should really be done in an SQL query, but we already load the submits into memory at a couple of other places, so :shrug: The code for sorting the students would be so much nicer with iterators :(

Add link to the next unevaluated submit to teacher submit view

---

templates/web/task_detail.html

There should always be a source code available, because we know that there is at least a single submit for the given student, otherwise the link wouldn't point to it.
Suggested by Pavel Dohnálek.

Make the "Next student to evaluate" link point directly to source code
