common/admin.py
Displays only teacher logins in the filter box. Fixes Issue #2
=> Fix: Filter by teacher in admin

common/admin.py
=> Class column in AssignedTask admin view

common/admin.py
=> Class filter in AssignedTask admin view

web/views/teacher.py
Pokud nějaký student neměl ohodnocený úkol, tak tato obrazovka vyhazovala chybu.
=> Fix task results view if some student does not have result yet

web/views/student.py
Fixes: https://github.com/mrlvsb/kelvin/issues/25
=> Extract uploaded ZIP files

web/static/comments.vue, web/static/style.css
Added border and automatic wrapping:
=> Change design of source code comments

templates/web/layout.html, templates/web/task_detail.html, web/static/comments.vue, web/static/global.js, web/static/style.css, web/task_utils.py, web/views/student.py
Fixes: https://github.com/mrlvsb/kelvin/issues/42
=> Add copy source file text button

common/models.py, templates/web/layout.html, templates/web/teacher/form_assign_points.html, web/apps.py, web/static/notifications.vue, web/views/student.py, web/views/teacher.py
Fixes: https://github.com/mrlvsb/kelvin/issues/43
=> Notifications

web/static/notifications.vue
Ať jednoduše vidíme, kdy to přesně odevzdali :-)
=> Show precise time in notification

web/static/comments.vue, web/static/style.css, web/views/student.py
=> Colorize comments based on their author

common/moss.py
Submits with multiple source files are merged together to avoid false self-plagiarism positives in MOSS.
=> Merge submit source files into a single file for MOSS check

frontend/src/Manager.svelte, frontend/src/fs.js
Fixes: https://github.com/mrlvsb/kelvin/issues/58
=> File manager improvements

frontend/src/ClassDetail.svelte, frontend/src/EditTask.svelte, requirements.txt, templates/web/teacher/statistics.html, web/urls.py, web/views/statistics.py
TODO:
Closes https://github.com/mrlvsb/kelvin/issues/24
=> Add basic task submit statistics

templates/web/moss.html, web/urls.py, web/views/student.py, web/views/teacher.py
Fixes: https://github.com/mrlvsb/kelvin/issues/126, https://github.com/mrlvsb/kelvin/issues/127
=> Improve MOSS UX

common/moss.py, frontend/src/Notifications.svelte, kelvin/settings.py, requirements.txt, templates/web/moss.html, web/views/teacher.py
Fixes: https://github.com/mrlvsb/kelvin/issues/124
=> Moss periodic check

frontend/src/EditTask.svelte, templates/web/submits_show_source.html, web/urls.py, web/views/teacher.py
Improvements:
1) Allow toggling all source codes to enable quick searching in browser
2) Allow showing source codes for a whole task, not just a specific assignment
Fixes: https://github.com/mrlvsb/kelvin/issues/104
=> Improve source code show

web/views/student.py, web/views/upload.py
Two students sent me their `venv` directories :man_facepalming:
=> Avoid upload DDOS

evaluator/pipelines.py
```yaml
pipeline:
- type: run
before:
- echo 1 > /test
commands:
- cat /test
```
=> pipeline supports image modification with "before"

frontend/package-lock.json, frontend/package.json, frontend/src/Editor.svelte, frontend/src/Manager.svelte, frontend/src/PipelineValidation.js
Linter for config.yml, autocomplete feature can be triggered by ctrl+space
=> config.yml pipeline linter & autocomplete

frontend/src/Notifications.svelte
**Changes**:
- Added better error message which help strict browser users (like Brave) to fix problem with notifications.
=> Notifications - Improved error message when notification registration fails.

frontend/src/Notifications.svelte
Fixed typo in push notifications alert 
"in" -> "is"
=> Fixed typo

templates/web/task_detail.html
Date and time of submit is sometimes needed if its long overdue.
Please, check if it works. I'm kind of bling without a working devel version :-)
=> Always display submit time

frontend/src/CodeRow.svelte, frontend/src/Notifications.svelte, frontend/src/TaskDetail.svelte
Probably a bad practice :D possibly is there any easy way to force rerender? Or should be scroll moved outside the component?
=> Scroll into view when clicking comment notification even if already selected

evaluator/images/base/Dockerfile, evaluator/pipelines.py
=> Produce a better error when a test times out

templates/web/task_detail.html
=> first-last

Dockerfile, templates/web/moss.html, web/urls.py, web/views/student.py, web/views/teacher.py, web/views/utils.py
Fixes: https://github.com/mrlvsb/kelvin/issues/213
=> Add button for downloading anonymized plagiarism graph to MOSS page

requirements.txt
=> Revert "build(deps): bump markupsafe from 2.0.1 to 2.1.2"

api/views.py, common/moss.py, common/moss/__init__.py, common/moss/local_result.py, frontend/src/ClassDetail.svelte, frontend/src/EditTask.svelte, requirements.txt, templates/web/moss.html, web/urls.py, web/views/teacher.py
This PR contains various small MOSS UX improvements. After the refactoring, the MOSS Redis cache will have to be flushed, otherwise the MOSS page will crash.
If the redis data is persistent, it will probably be easier to just remove some of the refactoring changes to avoid the need to migrate the data.
The PR also adds local caching of MOSS results.
Fixes: https://github.com/mrlvsb/kelvin/issues/181
=> Various MOSS UX improvements

frontend/src/ClassDetail.svelte
Solves: #178 
I've added the total points per assignment in the class of students. 
Here is what it looked like before: [Click here](https://ctrlv.link/jlOy) (There is nothing in the bottom row of the table)
Here is what it looks like now: [Click here](https://ctrlv.link/Vzt4) (There is sum of points per assignment in the bottom row of the table)
=> Total points per assigned task #178

api/views.py, common/inbus.py, common/utils.py, requirements.txt
Partially solves #193 .
This if the first INBUS API call we can make. More to come.
=> INBUS integration to get user info

frontend/src/ClassDetail.svelte
I added a bit more information to the new task summary row.
CC @tomasmensik
=> Add text summary to task point sum

common/inbus.py, common/management/commands/fill_user_info.py, common/utils.py
INBUS API response may have missing fields. So at this point simeple dict.get with default is used. Maybe we can use something like Dacite and default values in dataclass.
=> Use INBUS API to fill user info instead of LDAP

common/moss/__init__.py, templates/web/moss.html, web/views/moss.py
=> Show linked tasks on MOSS page

templates/web/index.html
Fixes: https://github.com/mrlvsb/kelvin/issues/288
=> Hide class summary by default and add a button to show it

templates/web/task_detail.html, web/views/student.py
=> Add pipeline result icon to Result tab

templates/web/moss.html, web/views/moss.py
So that we have a better idea of where do the tasks come from.
=> Show semester(s) where a linked task was assigned in MOSS page

templates/web/task_detail.html
And remove extra space after deadline.
=> Remove debug outputs created in a previous PR by accident

frontend/src/CommentForm.svelte, frontend/src/Editor.svelte
Fixes https://github.com/mrlvsb/kelvin/issues/302.
=> Use wrapping instead of scrolling for source code comments

templates/web/task_detail.html
=> Fix next button missing when 2 submits (#310)

evaluator/images/base/Dockerfile, evaluator/images/dotnet/Dockerfile, evaluator/images/dotnet/entry.py, evaluator/images/pythonrun/Dockerfile
Fixes: https://github.com/mrlvsb/kelvin/issues/323
=> Update docker images

kelvin/settings.py, templates/web/layout.html, web/views/common.py
So that it doesn't need to be applied using git working dir modifications.
=> Allow configuring sentry URL

web/views/student.py
Apparently, opening `.tar.gz` on Windows is not that user friendly. This PR changes downloads of assets (like `template` or `assets` directories) do `.zip` archives. For backwards (and honestly, forwards) compatibility with existing/future links in task READMEs, both `.tar.gz` and `.zip` will now download a `.zip` archive. 
Fixes: https://github.com/mrlvsb/kelvin/issues/301
=> Download asset archives as `.zip`

api/urls.py, api/views.py, frontend/src/ClassFilter.svelte, frontend/src/ClassList.svelte, frontend/src/StudentTransfer.svelte
Fixes: https://github.com/mrlvsb/kelvin/issues/313
=> Add class filter to teacher homepage

web/views/student.py
=> Synchronize student semester label with Edison

web/views/student.py, web/views/upload.py
Fixes: https://github.com/mrlvsb/kelvin/issues/315
=> Return a better error message when a student uploads too many files

frontend/src/TaskDetail.svelte
Fixes: https://github.com/mrlvsb/kelvin/issues/174
=> Move to first/last submit using Shift+Left/Right arrow keys

templates/web/task_detail.html, web/views/student.py
The submit detail page now shows top 5 detected plagiarisms. Note that this is not necessarily shown for the selected submit! Just for any submit of the student that was checked.
Fixes: https://github.com/mrlvsb/kelvin/issues/319
=> Show plagiarism on task detail page

frontend/src/AssignmentPoints.svelte, frontend/src/ClassDetail.svelte, frontend/src/ColorTheme.svelte, frontend/src/Notifications.svelte, frontend/src/global.css, templates/web/index.html, templates/web/layout.html, templates/web/moss.html, templates/web/submits_show_source.html, templates/web/task_detail.html, web/views/student.py
Fixes: https://github.com/mrlvsb/kelvin/issues/337
=> Fix underscore of links

frontend/src/TaskDetail.svelte
Fixes: https://github.com/mrlvsb/kelvin/issues/336
=> Collapse files by default in task detail page

evaluator/images/dotnet/Dockerfile
They were being removed from APT.
=> Relax .NET APT packages in Docker

common/bulk_import.py, common/inbus/dto.py, frontend/src/ImportFromInbus.svelte
This is a nasty hack that adds subject version to Subject.code.
A nicer fix is welcome.
=> INBUS: Fix importing of multiple subject versions

templates/web/index.html
Regression introduced by upgrade to Bootstrap 5. Found by @adaxiik (thanks!).
=> Fix collapse of Class notes button

README.md, evaluator/images/gcc/entry.py, kelvin/settings.py, requirements.txt
Sometimes students were confused by the fact that a successful
compilation yielded no positive message, or by the fact that the
compiler spat out multiple warnings which the students were unable to
distinguish from errors. Therefore, we want Kelvin to return some form
of a positive feedback for the peace of mind of our students.
=>  Include positive feedback when compilation succeeds 

evaluator/images/gcc/entry.py
=> Use div for gcc messages

evaluator/pipelines.py, frontend/src/PipelineValidation.js
This allows us e.g. to use Valgrind in tests
=> Allow passing a list of commands to test

evaluator/pipelines.py
It is causing problems when the program output… contains whitespace :)
=> Do not ignore whitespace when checking tests

common/management/commands/kelvin_edison_difference.py
The script prints all classes and students that should be attend a different class.
=> Kelvin vs Edison schedule difference script

frontend/src/ClassDetail.svelte
=> ClassDetail: Treat null as NaN

frontend/src/EditTask.svelte
I have refactored the use of Bootstrap modal in `EditTask.svelte` to use `Modal.svelte` component, as committed in #375.
After this change, the confirm button in the modal does not have `btn-danger` class but `btn-primary`. If needed, I could add an extra prop to `Modal.svelte` to allow changing button classes.
=> EditTask: Use Modal component

common/admin.py
This is useful when creating a lot of classes manually, for example, when creating classes for tests.
=> Enable 'Save as new' in class admin.

common/moss/__init__.py, templates/web/moss.html, web/views/moss.py
A small bandaid to try to fix MOSS timeouts/connection refusals.
=> Add submit limit to MOSS check

frontend/src/CodeRow.svelte
Supersedes: https://github.com/mrlvsb/kelvin/pull/380.
CC @DanielKrasny
=> Update colors of code comments in dark mode

api/views.py, common/bulk_import.py, common/inbus/inbus.py, common/utils.py
This implements importing of classes that are taught by multiple teachers. Since we support only one teacher per class, the teacher is taken from the current "user/teacher" who's importing the class.
=> Enable importing of classes with multiple teachers

evaluator/images/gcc/entry.py, frontend/src/main.js
A bunch of fixes to get CPP I pipeline working. The `AnsiUp` usage was broken in https://github.com/mrlvsb/kelvin/pull/402.
=> Various fixes for CPP I

common/bulk_import.py
This variable overrides parameter of the import function, which ends up in the wrong teacher assigned to the class.
=> Rename variable used for student user in import (#435)

frontend/src/Comment.svelte, frontend/src/TaskDetail.svelte, frontend/src/stores.js
I've added checkboxes to source code view for temporarily hiding comments.
https://github.com/mrlvsb/kelvin/assets/18398260/d7f11ed5-0329-4fe7-8a5e-b78343b601ee
=> Adding checkboxes to hide comments

api/views.py
Also removed or added blank lines to make linter happy.
=> Removed unused imports

.github/workflows/codeql-analysis.yml
Also update the `checkout` action to v4.
=> Update CodeQL Analysis to v3

common/moss/__init__.py
It's not a full fix, but should hopefully help for now.
Fixes: https://github.com/mrlvsb/kelvin/issues/452
=> Check if extension is in counter dictionary in MOSS check

api/views.py, common/models.py
=> Changed `id` to `pk` in model lookups

requirements.txt
Package is installed in production. The version is the same.
=> List `lxml` package in `requirements.txt`

.github/workflows/deploy.yml
Use the `production` environment and its secrets to deploy code from `master`.
=> Manage deployments through environments

.env.example, README.md, docker-compose.yml, docs/architecture.md, docs/development.md, docs/setup.md, kelvin/settings.py
Also simplify the provided Docker compose file to only provide the most useful things needed for local development.
The rendered Mermaid diagram can be found [here](https://github.com/mrlvsb/kelvin/blob/023a9e992f0ab360277725720c75ec1c4cf0be3d/docs/architecture.md).
=> Rewrite README of Kelvin and add basic developer documentation

api/urls.py, api/views.py, common/submit.py, common/upload.py, kelvin/settings.py, web/urls.py, web/views/student.py
I want this functionality to create `cargo kelvin` for making it simpler to upload (Rust) submits into Kelvin.
=> Add API for submitting tasks

frontend/.prettierignore, frontend/.prettierrc, frontend/eslint.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/rollup.config.js, frontend/src/ExampleComponent.vue, frontend/src/main.js, frontend/tsconfig.json
Added support for using Vue and Typescript in frontend. 
Added Prettier + Eslint for linting and formatting frontend files.
=> Added support for Vue + Typescript and added eslint + prettier

frontend/.prettierignore, frontend/.prettierrc, frontend/eslint.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/rollup.config.js, frontend/src/ExampleComponent.vue, frontend/src/main.js, frontend/tsconfig.json
Added support for using Vue and Typescript in frontend.
Added Prettier + Eslint for linting and formatting frontend files.
Fixing #511
=> Added support for Vue + Typescript and added eslint + prettier (atempt 2)

.github/workflows/test.yml, frontend/eslint.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/src/PipelineValidation.js, frontend/src/api.js, frontend/src/fs.js, frontend/src/global.css, frontend/src/global.js, frontend/src/global.scss, frontend/src/main.js, frontend/src/markdown.js, frontend/src/notifications.js, frontend/src/stores.js, frontend/src/utils.js, frontend/tsconfig.json
=> Add frontend tests on CI

.github/workflows/test.yml, frontend/eslint.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/src/PipelineValidation.js, frontend/src/api.js, frontend/src/fs.js, frontend/src/global.css, frontend/src/global.js, frontend/src/global.scss, frontend/src/main.js, frontend/src/markdown.js, frontend/src/notifications.js, frontend/src/stores.js, frontend/src/utils.js, frontend/tsconfig.json
Reverts because of bundler issues.
=> Revert "Add frontend tests on CI"

evaluator/images/base/Dockerfile, evaluator/images/dotnet/Dockerfile, evaluator/images/pythonrun/Dockerfile
This includes an update to .NET 8.
Fixes: https://github.com/mrlvsb/kelvin/issues/521
=> Updates base Docker image to Ubuntu 24.04

common/submit.py
I broke this in https://github.com/mrlvsb/kelvin/pull/495 :(
Found by @patrick11514 :heart:
=> Fix submit notifications

web/views/student.py
I want to see if this is causing the slow load of some student's submit pages.
=> Remove plagiarism SVG graph rendering

common/plagcheck/moss/__init__.py, templates/web/plagcheck.html, web/views/plagcheck.py, web/views/student.py
The SVG generation can be quite slow, this should make both submit and plagiarism page loading much faster.
=> Remove plagiarism graph from result page

evaluator/images/java/Dockerfile
=> Revert "Add support for Java 21 (#527)"

frontend/src/ClassDetail.svelte
=> Add direct link to class to edit in Admin

.env.example, Dockerfile, deploy/entrypoint.sh, docker-compose.yml, kelvin/settings.py
A couple of changes that I made while deploying Kelvin to a new server.
=> Deployment improvements

api/urls.py, api/views.py, common/inbus/inbus.py, common/inbus/views.py, frontend/src/Teacher/InbusImport.vue
This removes harcoded INBUS semester id.
=> Use INBUS semester to get subject schedule

deploy/entrypoint.sh, frontend/src/Teacher/InbusImport.vue
Due to interactions of Docker volumes, we have to rebuild static files each time the Docker image is started, otherwise we will get stale data.
=> Fix collection of static items in Docker

frontend/src/Teacher/InbusImport.vue
It was added just temporarily to test deployment.
=> Remove test log

evaluator/images/run/Dockerfile
Just add java package to dockerfile for "run" pipeline
=> feat(pipeline):add java 21 into dockerfile (#597)

frontend/src/StudentTransfer.svelte
Somehow, the fix from previous semester doesn't work anymore. So reverting this change.
Solves #616
=> [Fix] Student transfer hotfix

pyproject.toml, uv.lock, web/signals.py
Just to see if everything works in our current deployment.
=> Basic logging of IP addresses

web/views/student.py
=> Check if comment source file is available in submit

templates/web/index.html
=> Clearly display to student if there is a submit to a task

evaluator/pipelines.py
This is requested by our colleagues
=> Enable internet connection for `run` docker image

frontend/src/ClassDetail.svelte, frontend/src/Teacher/StudentList.vue, frontend/src/Teacher/StudentPage.vue, frontend/src/main.js, templates/web/layout.html, templates/web/student_page.html, templates/web/task_detail.html, web/urls.py, web/views/teacher.py
It doesn't really contain anything useful yet, but I wanted to get the infrastructure in, so that adding stuff to the page can be done with follow-up PRs.
=> Add basic student page

.github/workflows/ci.yml, uv.lock
Another CI check that we were missing :)
=> Add CI check that the lockfile is up-to-date

frontend/src/Teacher/TaskList.vue
It should be using 24-hour format, not 12-hour format.
=> Fix hour format in task list table

deploy/nginx.conf
Again, not reason not to do this. I already modified the production nginx config.
=> Enable HTTP2 for nginx

kelvin/settings.py
=> Disable logs from the markdown crate

web/views/student.py
This is a bandaid rather than a proper fix, but the frontend FS implementation looks scary, and I got annoyed with seeing this in the logs all the time.
=> Handle move of non-existent files

frontend/src/TaskFilter.svelte
Fixes #668
Sorry about that, should look like this now.
=> Fixed task_type filter light mode

.github/workflows/ci.yml
It seems that uwsgi fails to be installed on CI now..
=> Install C/C++ compiler on CI

docs/setup.md
So we don't stay behind the current `uv` version :-)
=> Remove mention of specific `uv` version in setup doc

frontend/package-lock.json, frontend/package.json, frontend/src/Teacher/student-page/EventList.vue
It's a bit stringy, bulky, and in frontend but at this point it's good enough?
=> Clearly display if IP addresses if from our labs
